services:
  - type: web
    name: morph-app-backend
    env: node
    buildCommand: cd server && pnpm install && pnpm run build
    startCommand: cd server && pnpm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://morph-app-client.onrender.com
      - key: REDIS_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: morph-app-frontend
    env: node
    buildCommand: cd client && pnpm install && pnpm run build
    startCommand: cd client && pnpm preview --host
    rootDir: client
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://morph-app.onrender.com
    autoDeploy: true
